function elbo_latent_precision(obj)

    if ~isfinite(obj.nz0) || obj.nz0 == 0
        obj.lbAz = 0;
    else
        obj.lbAz =   0.5 * obj.nz0 * (obj.logAz - gpca.utils.logdetPD(obj.Az0))...
                   - 0.5 * obj.nz0 * log(obj.nz/obj.nz0) ...
                   - 0.5 * obj.nz0 * trace(gpca.utils.invPD(obj.Az0)*obj.Az) ...
                   + 0.5 * obj.nz * obj.M ...
                   - gpca.utils.logGamma(0.5*obj.nz0,obj.M) ...
                   + gpca.utils.logGamma(0.5*obj.nz,obj.M) ...
                   + 0.5 * (obj.nz0-obj.nz) * gpca.utils.diGamma(0.5*obj.nz,obj.M);
    end

end