function obj = elbo_latent_precision(obj)

    if ~isfinite(obj.nA0) || obj.nA0 == 0
        obj.lbA = 0;
    else
        obj.lbA =   0.5 * obj.nA0 * (gpca.utils.logdetPD(obj.A) - gpca.utils.logdetPD(obj.A0))...
                  + 0.5 * obj.nA0 * obj.M * log(obj.nA0/obj.nA) ...
                  - 0.5 * obj.nA0 * trace(gpca.utils.invPD(obj.A0)*obj.A) ...
                  + 0.5 * obj.nA * obj.M ...
                  + gpca.utils.logGamma(0.5*obj.nA,obj.M) ...
                  - gpca.utils.logGamma(0.5*obj.nA0,obj.M) ...
                  + 0.5 * (obj.nA0-obj.nA) * gpca.utils.diGamma(0.5*obj.nA,obj.M);
    end

end